### ISSUE TITLE
AMLStudio: Combobox for connection selection

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#12]
Change the "Change" Button into a Combobox. See #5

**Comment by erdomke** [comment]
Since you can double click an item in the editor to select it (or use Ctrl+O > arrow keys > Enter if you are keyboard-minded), I feel that the current UI is nearly as efficient as a combobox with the added usability that added and/or modifying connections does not require going to a separate UI.  Therefore, I am going to close this for now.
