### ISSUE TITLE
Query is reset when connection is changed

### ISSUE THREAD

**Issue by DavidSpackman** [erdomke/InnovatorAdmin#126]
When you change your connection the current query is cleared and the last saved query will be set for the new connection.

Is this be design?

Sometimes not ideal if you want to create a query in one connection and then make to apply to another connection.

Tool is looking awesome by the way.

**Comment by rneuber1** [comment]
This seems to be a feature: the tool remembers the last query for every connection and sets this upon connection change.
I am not quite sure if I like that or not: When starting the application up, having the last AML available comes in handy, but on connection change, it often is not the desired behavior.

**Comment by erdomke** [comment]
It is by design, largely to account for the fact that an AML query won't work if I switch to a direct SQL connection.  For the next release I will tweak the behavior.  In particular, if there is existing text and you switch the connection to another of the same type (e.g. Innovator > Innovator), then the text will not be changed.  However, if the editor is empty, or you are switching the connection type (e.g. Innovator > SQL), then the text will be changed.
