### ISSUE TITLE
File Upload/Download

### ISSUE THREAD

**Issue by DavidSpackman** [erdomke/InnovatorAdmin#167]
Does Innoatoradmin support file upload/download?
I had a look in the wiki and couldnt see an example.

**Comment by erdomke** [comment]
Yes, it is supported.  I added documentation to the wiki under [Uploading and Downloading Files](https://github.com/erdomke/InnovatorAdmin/wiki/Uploading-and-Downloading-Files).  However, there is a small bug in the download code which I recently discovered.  It is fixed in the latest commit, but not yet in the latest release.
