### ISSUE TITLE
TOC not shown for Aras 11.0 SP9

### ISSUE THREAD

**Issue by mdvaras** [erdomke/InnovatorAdmin#179]
InnovatorAdmin v2016.6.7.1612 is not showing TOC since upgrade to Aras version 11.0 SP9. Upgrade was performed from version 11.0 SP7 where InnovatorAdmin worked well. Even though TOC is not shown, AML queries from the application work normally. The latest version was also recompiled but symptoms stayed the same.
Another not working part is creation of package. When package items are selected, InnovatorAdmin gets stuck on message "Loading system data".

**Comment by erdomke** [comment]
The latest release (which you might need to get manually since the automatic update does not seem to be working) should now work with the Innovator 11sp9 TOC.  If you add the file [ItemAnalysis.Suppressions.InnovatorAdmin.txt](https://github.com/erdomke/InnovatorAdmin/files/1079642/ItemAnalysis.Suppressions.InnovatorAdmin.txt) to the directory `{InstallationPath}\Innovator\Server\App_Data` on your Aras server, most of the import/export functions should also work.  (Note, you will need to change the extension from `*.txt` to `*.xml`.)  Eventually that file might not be needed, but it will be a bit before all those changes can take place.

**Comment by NoboruYamazakiJP** [comment]
Hi! erdomke,
I have installed innovator11.0 sp9, and copy the file - ItemAnalysis.Suppressions.InnovatorAdmin.xml
to ~/Innovator/Server/App_Data, but it is not work yet.
(TOC is not shown when logged in)
Help me, please.
Thanks!

**Comment by erdomke** [comment]
It only works with the latest release of Innovator Admin (
https://github.com/erdomke/InnovatorAdmin/releases/tag/v2017.06.15.2258).
Please make sure you are using that latest release.  If you are, and it
still doesn't work, let me know.

Eric

**Comment by NoboruYamazakiJP** [comment]
Hi! Eric!
Thank you for your reply.
I use Innovator 11.0 SP9 Build=6549.
I got your Innovator-Admin tool, and it works well.
Then how can I fix my problem? (no TOC be shown after logged in).
N.Yamazaki

**Comment by NoboruYamazakiJP** [comment]
I have re-installed innovator v11.0 SP9 with creating new DB, then it worked!
(Last time, I had tried to re-use the DB of old innovator (v11.0 SP0)).

How can I upgrade the old DB (InnovatorSolution110SP0) to the new DB (InnovatorSolution110SP9)?
Any idea is appreciated!

N.Yamazaki

**Comment by erdomke** [comment]
I'm glad it started working. The official answer to your question would be to pay for subscription and work with Aras (or one of their partners) to perform the upgrade.  The unofficial answer is that you basically have one of two options (that I can think of) depending on how much data you need to migrate:

- With your fresh new 11sp9 instance, migrate all of your customization and data into the new instance.  The customization migration should be just an import/export using either Innovator Admin or the tools provided by Aras.  Afterwards, I would probably use SQL to migrate the data in order to preserve states, created/modified dates, etc.
- Perform a three-way merge of the metadata.  Export the core metadata (ItemTypes, Lists, Reports, Methods, etc) out of each of the following configurations: a plain 11sp0 installation, a plain 11sp9 installation, and your actual installation.  Perform a 3-way merge of export scripts (using a source control tool such as git would help with this).  Once you have the final scripts, run them on a copy of your existing installation, and you should have an upgraded instance.

I hope that gives you some inspiration.
