### ISSUE TITLE
RunAll does not work (as expected)

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#58]
I would suppose that "Run All" would execute the queries in all open windows, yet this does not happen.

**Comment by erdomke** [comment]
The goal of "Run All" vs. "Run Current" is to allow you to have multiple queries in you window.  For example, you might have a query window which looks like 

    <AML>
      <Item>...</Item>
    </AML>

    <AML>
      <Item>.{CARET_HERE}..</Item>
    </AML>

In this situation, if you select "Run Current", it will run the second query (where the caret is).  However, if you select "Run All", it will attempt to run both queries (which will likely result in an error because there is no root element to the overall XML document).  Eventually, "Run Current" should also support running the current selection if multiple characters are selected (although this is not currently the case).
